apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - ../../../base/email-bridge
  - ../../../base/email-bridge-data
  - ../../../base/email-bridge-migration
