apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattercodex-system
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccounts-rbac.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - dashboard.yaml
components:
  - ../../components/internal-rpc-authority-runtime-controller-issuer
