apiVersion: v1
kind: ConfigMap
metadata:
  name: mattercodex-platform-endpoints
data:
  publicOrigin: __MATTERCODEX_PUBLIC_ORIGIN__
  oidcIssuer: __MATTERCODEX_OIDC_ISSUER__
  oidcJwksUrl: __MATTERCODEX_OIDC_JWKS_URL__
  oidcConnectAddress: __MATTERCODEX_OIDC_CONNECT_ADDRESS__
  oidcTlsServerName: __MATTERCODEX_OIDC_TLS_SERVER_NAME__
