apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattercodex-system
resources:
  - configmap.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - issuer-networkpolicy.yaml
  - prometheusrule.yaml
  - dashboard.yaml
  - vault-secret-provider-classes.yaml
components:
  - ../../components/internal-rpc-authority-integration-gateway-issuer
