apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: integration-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: integration-gateway
      app.kubernetes.io/component: integration-worker
