apiVersion: v1
kind: Service
metadata:
  name: integration-gateway
  labels:
    app.kubernetes.io/name: integration-gateway
    app.kubernetes.io/component: integration-worker
spec:
  selector:
    app.kubernetes.io/name: integration-gateway
    app.kubernetes.io/component: integration-worker
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
    - name: auth-metrics
      port: 9091
      targetPort: auth-metrics
      protocol: TCP
