-- name: platform__runtime_claimexecution_insert_runtime_revision :one
INSERT INTO control_plane.runtime_revisions (
    ref,
    organization_id,
    project_id,
    root_run_id,
    run_id,
    node_id,
    session_id,
    turn_id,
    agent_id,
    role_definition_id,
    role_image_recipe_id,
    role_image_artifact_id,
    provider_account_id,
    provider_credential_revision_id,
    generation,
    attempt,
    runtime_profile_key,
    runtime_profile_revision,
    provider,
    model,
    provider_account_ref,
    provider_credential_revision_ref,
    provider_credential_revision_number,
    provider_secret_name,
    provider_secret_uid,
    provider_secret_resource_version,
    provider_credential_sha256,
    instruction_ref,
    instruction_digest,
    input_digest,
    capabilities,
    integration_grants_digest,
    image_reference,
    image_manifest_digest,
    role_runtime_contract_revision,
    role_runtime_contract_sha256,
    revision_digest,
    safe_snapshot
)
VALUES (
    $1,
    $2::uuid,
    NULLIF($3, '')::uuid,
    $4::uuid,
    $5::uuid,
    $6::uuid,
    $7::uuid,
    NULLIF($8, '')::uuid,
    $9::uuid,
    $10::uuid,
    NULLIF($11, '')::uuid,
    NULLIF($12, '')::uuid,
    $13::uuid,
    $14::uuid,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25::uuid,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38
)
RETURNING id::text;
