package platform

import _ "embed"

var (
	//go:embed sql/context_bindings_list.sql
	queryContextBindingsList string
	//go:embed sql/context_binding_skill_files.sql
	queryContextBindingSkillFiles string
	//go:embed sql/context_binding_get.sql
	queryContextBindingGet string
	//go:embed sql/context_binding_count.sql
	queryContextBindingCount string
	//go:embed sql/context_binding_insert.sql
	queryContextBindingInsert string
	//go:embed sql/context_binding_update.sql
	queryContextBindingUpdate string
	//go:embed sql/context_binding_memory_target.sql
	queryContextBindingMemoryTarget string
	//go:embed sql/context_binding_skill_target.sql
	queryContextBindingSkillTarget string
	//go:embed sql/skill_bundle_list.sql
	querySkillBundleList string
	//go:embed sql/skill_revision_list.sql
	querySkillRevisionList string
	//go:embed sql/skill_revision_transition.sql
	querySkillRevisionTransition string
	//go:embed sql/skill_bundle_transition.sql
	querySkillBundleTransition string
	//go:embed sql/skill_bundle_disable_bindings.sql
	querySkillBundleDisableBindings string
	//go:embed sql/skill_bundle_purge.sql
	querySkillBundlePurge string
	//go:embed sql/skill_artifact_content.sql
	querySkillArtifactContent string
	//go:embed sql/skill_revision_validate.sql
	querySkillRevisionValidate string
	//go:embed sql/skill_bundle_get.sql
	querySkillBundleGet string
	//go:embed sql/skill_bundle_insert.sql
	querySkillBundleInsert string
	//go:embed sql/skill_bundle_lock.sql
	querySkillBundleLock string
	//go:embed sql/skill_revision_insert.sql
	querySkillRevisionInsert string
	//go:embed sql/skill_revision_save.sql
	querySkillRevisionSave string
	//go:embed sql/skill_bundle_set_draft.sql
	querySkillBundleSetDraft string
	//go:embed sql/skill_artifact_get.sql
	querySkillArtifactGet string
	//go:embed sql/memory_revision_get.sql
	queryMemoryRevisionGet string
	//go:embed sql/memory_record_list.sql
	queryMemoryRecordList string
	//go:embed sql/memory_revision_list.sql
	queryMemoryRevisionList string
	//go:embed sql/memory_record_get.sql
	queryMemoryRecordGet string
	//go:embed sql/memory_record_lock.sql
	queryMemoryRecordLock string
	//go:embed sql/memory_record_insert.sql
	queryMemoryRecordInsert string
	//go:embed sql/memory_revision_insert.sql
	queryMemoryRevisionInsert string
	//go:embed sql/memory_record_set_revision.sql
	queryMemoryRecordSetRevision string
	//go:embed sql/memory_record_set_state.sql
	queryMemoryRecordSetState string
	//go:embed sql/memory_record_purge.sql
	queryMemoryRecordPurge string
	//go:embed sql/memory_record_disable_bindings.sql
	queryMemoryRecordDisableBindings string
)
