package platform

import _ "embed"

var (
	//go:embed sql/permissions_authorizecommand_select_memberships_organization_id_project_id_subject_id.sql
	queryPermissionsAuthorizecommandSelectMembershipsOrganizationIdProjectIdSubjectId string
	//go:embed sql/permissions_requireprojectpermission_select_memberships_organization_id_project_id_subject_id.sql
	queryPermissionsRequireprojectpermissionSelectMembershipsOrganizationIdProjectIdSubjectId string
	//go:embed sql/permissions_list_project_permissions.sql
	queryListProjectPermissions string
	//go:embed sql/permissions_projectidbyresource_select_projects_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectProjectsOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_agents_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectAgentsOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_workflows_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectWorkflowsOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_sessions_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectSessionsOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_runs_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectRunsOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_owner_gates_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectOwnerGatesOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_artifacts_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectArtifactsOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_schedules_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectSchedulesOrganizationIdRef string
	//go:embed sql/permissions_projectidbyresource_select_assistant_conversations_organization_id_ref.sql
	queryPermissionsProjectidbyresourceSelectAssistantConversationsOrganizationIdRef string
)
