package platform

import _ "embed"

var (
	//go:embed sql/artifacts_uploadartifact_select_idempotency_receipts_organization_id_actor_id_operation.sql
	queryArtifactsUploadartifactSelectIdempotencyReceiptsOrganizationIdActorIdOperation string
	//go:embed sql/artifacts_uploadartifact_select_runs_organization_id_project_id_ref.sql
	queryArtifactsUploadartifactSelectRunsOrganizationIdProjectIdRef string
	//go:embed sql/artifacts_uploadartifact_insert_artifacts_ref_project_id_file_name.sql
	queryArtifactsUploadartifactInsertArtifactsRefProjectIdFileName string
	//go:embed sql/artifacts_uploadartifact_insert_artifact_content_artifact_id.sql
	queryArtifactsUploadartifactInsertArtifactContentArtifactId string
	//go:embed sql/artifacts_uploadartifact_insert_audit_events_ref_project_id_action.sql
	queryArtifactsUploadartifactInsertAuditEventsRefProjectIdAction string
	//go:embed sql/artifacts_uploadartifact_insert_idempotency_receipts_organization_id_operation_intent_digest.sql
	queryArtifactsUploadartifactInsertIdempotencyReceiptsOrganizationIdOperationIntentDigest string
	//go:embed sql/artifacts_downloadartifact_select_artifact_for_grant.sql
	queryArtifactsDownloadartifactSelectArtifactForGrant string
	//go:embed sql/artifacts_downloadartifact_insert_download_grant.sql
	queryArtifactsDownloadartifactInsertDownloadGrant string
	//go:embed sql/artifacts_downloadartifact_consume_download_grant.sql
	queryArtifactsDownloadartifactConsumeDownloadGrant string
	//go:embed sql/artifacts_downloadartifact_select_artifact_content.sql
	queryArtifactsDownloadartifactSelectArtifactContent string
	//go:embed sql/artifacts_downloadartifact_insert_audit_event.sql
	queryArtifactsDownloadartifactInsertAuditEvent string
	//go:embed sql/artifacts_changeartifactbinding_select_artifacts_organization_id_ref_scan_state.sql
	queryArtifactsChangeartifactbindingSelectArtifactsOrganizationIdRefScanState string
	//go:embed sql/artifacts_changeartifactbinding_select_agents_organization_id_project_id_ref.sql
	queryArtifactsChangeartifactbindingSelectAgentsOrganizationIdProjectIdRef string
	//go:embed sql/artifacts_changeartifactbinding_insert_artifact_bindings_artifact_id_target_ref.sql
	queryArtifactsChangeartifactbindingInsertArtifactBindingsArtifactIdTargetRef string
	//go:embed sql/artifacts_changeartifactbinding_delete_artifact_bindings_artifact_id_target_kind_target_ref.sql
	queryArtifactsChangeartifactbindingDeleteArtifactBindingsArtifactIdTargetKindTargetRef string
	//go:embed sql/artifacts_changeartifactbinding_update_artifacts_version.sql
	queryArtifactsChangeartifactbindingUpdateArtifactsVersion string
	//go:embed sql/artifacts_changeartifactbinding_update_agents_version.sql
	queryArtifactsChangeartifactbindingUpdateAgentsVersion string
)
