{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "kodex-system",
  "resources": [
    "bootstrap.yaml",
    "service.yaml",
    "certificate.yaml",
    "serviceaccount.yaml",
    "statefulset.yaml",
    "networkpolicy.yaml"
  ]
}
