{
  "apiVersion": "networking.k8s.io/v1",
  "kind": "NetworkPolicy",
  "metadata": {
    "name": "email-bridge-postgresql",
    "namespace": "kodex-system",
    "labels": {
      "app.kubernetes.io/name": "email-bridge-postgresql"
    }
  },
  "spec": {
    "podSelector": {
      "matchLabels": {
        "app.kubernetes.io/name": "email-bridge-postgresql"
      }
    },
    "policyTypes": [
      "Ingress",
      "Egress"
    ],
    "ingress": [
      {
        "from": [
          {
            "namespaceSelector": {
              "matchLabels": {
                "kubernetes.io/metadata.name": "kodex-system"
              }
            },
            "podSelector": {
              "matchLabels": {
                "app.kubernetes.io/name": "email-bridge"
              }
            }
          },
          {
            "namespaceSelector": {
              "matchLabels": {
                "kubernetes.io/metadata.name": "kodex-system"
              }
            },
            "podSelector": {
              "matchLabels": {
                "app.kubernetes.io/name": "email-bridge-migration"
              }
            }
          }
        ],
        "ports": [
          {
            "protocol": "TCP",
            "port": 5432
          }
        ]
      }
    ],
    "egress": []
  }
}
